### ISSUE TITLE
Currency converter doesn't work

### ISSUE THREAD

**Issue by andrerodrigues6** [biati-digital/alfred-calculate-anything#100]
Like mentioned above, the currency converter doesn't work, however, everything else works (weight, dimensions, etc).

For example, if I type '188 cny' I get a short "Updating currency rates..." and it doesn't return anything.

How can I fix this issue? I have to go back to spotlight to get my currency conversions.

**Comment by biati-digital** [comment]
Please use the correct template to post bugs
