### ISSUE TITLE
Persistent calculations

### ISSUE THREAD

**Issue by GatCode** [biati-digital/alfred-calculate-anything#109]
With Spotlight, a user can type numbers, close spotlight, reopen it and the same input number will be there and can be used. Super handy for calculations with multiple numbers that must be copy-pasted. Is such persistent setting also available in calculate anything or Alfred in general?

**Comment by biati-digital** [comment]
Not related to this workflow but Alfred can do that

![CleanShot 2023-04-12 at 08 49 43](https://user-images.githubusercontent.com/1219228/231495851-4877b4c2-6109-4b85-9ee6-7a56d88f8876.png)

For Alfred related questions please use the https://www.alfredforum.com/
