### ISSUE TITLE
Automatically show base currency results after number without typing the currency symbol

### ISSUE THREAD

**Issue by yli** [biati-digital/alfred-calculate-anything#11]
For the people who use more than one base currency, it's frequent for us to convert among them. 

For instance, I personally use CNY and USD as my two base currencies. More than 99%, I convert from CNY to USD, or vice versa. 

It's helpful if it can automatically show several base-to-base currency conversion results once I type in the number without declaring the currency symbol (or else leave this as an option for convenience).

An example from [another currency workflow](https://github.com/tomy0000000/Coinc) showed as below:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/32441766/92325401-ff6a7800-f07c-11ea-844e-b227b691d8f6.png">

While in this workflow, it's not that smart:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/32441766/92325888-89681000-f080-11ea-8525-6482704be910.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/32441766/92325893-8ff68780-f080-11ea-812f-2f374911db5e.png">

**Comment by biati-digital** [comment]
i'm sorry, this is not possible, this workflow bypasses the keyword but a currency is necessary to let the workflow that you want to do a conversion, for example in the first workflow you have to type the keyword **cur** to activate the workflow, when you type 100 that workflow is the only one active so it nows you want to do the conversion for 100 

if you start typing 100 it might be that you only want to sum, multiply, divide two numbers, this workflow will be performing calculations when it's not necessary and showing conversion results that you are not expecting.
