### ISSUE TITLE
Workflow not working: Unable to run taksk

### ISSUE THREAD

**Issue by nachosdesign** [biati-digital/alfred-calculate-anything#115]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Before creating an issue make sure you are using the latest version, you can find the latest version in the [releases page](https://github.com/biati-digital/alfred-calculate-anything/releases)

**Describe the bug**

**To Reproduce**
1. Open Alfred
1. Type any number
2. See error:
> Unable to run task!
> Reason: launch path not accessible
> /usr/bin/php
> Check that the selected language exists on your system.
> If you're syncing Alfred's preferences, also check that all related workflow files exist locally.

**Expected behavior**
Expect it to work

**System information:**
 - OS: Mac OS 13.2.1
 - Alfred 5.1
- PHP Version -Not found

**Additional context*

**Comment by biati-digital** [comment]
Duplicate [https://github.com/biati-digital/alfred-calculate-anything/issues/114#issuecomment-1533339292](https://github.com/biati-digital/alfred-calculate-anything/issues/114#issuecomment-1533339292)
