### ISSUE TITLE
Unable to run task!

### ISSUE THREAD

**Issue by moshawin** [biati-digital/alfred-calculate-anything#116]
When I enter a number into the search bar, I get an error. It's horrible! What should I do?
<img width="296" alt="CleanShot 2023-05-14 at 16 44 45@2x" src="https://github.com/biati-digital/alfred-calculate-anything/assets/62423031/b892658d-1812-45c8-a3be-e52efb85d140">

**Comment by biati-digital** [comment]
Duplicate https://github.com/biati-digital/alfred-calculate-anything/issues/114#issuecomment-1533339292

**Comment by moshawin** [comment]
I didn't get a response.  How can you close a question if it is not answered?
