### ISSUE TITLE
Feature request include satoshis as a unit

### ISSUE THREAD

**Issue by matthiasdebernardini** [biati-digital/alfred-calculate-anything#12]
If I add support for satoshis (the smallest unit for a bitcoin) will you merge it in? I convert between these every day.

**Comment by biati-digital** [comment]
Pull requests are welcome, the changes must be done in workflow/tools/cryptocurrency.php we'll review the changes and if everything is ok we'll merge it.

**Comment by biati-digital** [comment]
Closing this, feel free to submit a pull request any time you want
