### ISSUE TITLE
Convert Time Correctly

### ISSUE THREAD

**Issue by falchion10** [biati-digital/alfred-calculate-anything#120]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Yes, current latest version is 4.0.2

**Describe the bug**
For reference, my time is UTC-5 (America/Chicago)

When I type "time utc" it gives me my current time, not the time in UTC. This happens with all timezones, not just UTC. The Timespan is also incorrect, it shows "5 hours ago" but UTC is not 5 hours behind me, it is 5 hours ahead. It should show "5 hours ahead".

When I type "time 12pm utc" it gives me 12pm in my timezone, it should show 7am. This should display my time - 5 hours because when it's 12pm in UTC it would be 7am in America/Chicago time. The timespan is correct on this one, showing how far away it is from 12pm UTC time.

**To Reproduce**
1. Open Alfred
1. Type "time utc" or "time 12pm utc"
2. You will see that it displays your current time.

**Expected behavior**
It should show me the time in the timezone I typed out. For instance for me it should show my time + 5 hours since Chicago is 5 hours behind UTC. It should also show what time it would be for me in the specified timzone (e.g. "time 12pm utc" would show 7am for me"

**Debug Output**
<img width="1239" alt="debugoutput" src="https://github.com/biati-digital/alfred-calculate-anything/assets/122236745/603eb3b7-4100-48df-8e41-30c84d183076">

<img width="1448" alt="debugoutput2" src="https://github.com/biati-digital/alfred-calculate-anything/assets/122236745/8db8c2d6-f960-4ce9-8ab3-ed76f97c1adc">

Please enable debug (see image) open Alfred and type the conversion that it's not working, you will see that the debug window is populated with a lot of text, please paste that text in here.

**System information:**
 - OS: macOS Sonoma 14.0 (21A5257q) 
 - Alfred Version: 5.1.1 [2138]
- PHP Version: 8.2.6

**Additional context**
This is basically a bump of [Issue #46](https://github.com/biati-digital/alfred-calculate-anything/issues/46) as it has been almost 2 years with seemingly no update on if this will be changed.

**Comment by biati-digital** [comment]
This is not a bug, using time utc will not work because that simply does not exist in the workflow.

You can upvote the existing issue or even better submit a PR to add this functionality.
