### ISSUE TITLE
Paste does not work on regular calculations like ex: (3*4=12)

### ISSUE THREAD

**Issue by yarub123** [biati-digital/alfred-calculate-anything#123]
However, paste does work for percentages and currencies 😞. 

For the regular calculations as in example above it only copies to clip but doesn't paste to frontmost app. The other ones do. Even if you hold modifiers nothing shows up...but for VAT and currencies the modifiers do show changed subtext and paste options...

Edit: nvm i think that's the default calculator in Aflred 🤦‍♂️

I wish it would paste to frontmost though upon hitting 'return'

**Comment by biati-digital** [comment]
Yes, that's Alfred not this workflow.

You can modify the workflow to your needs, just double click here (see screenshot) and enable "Automatically paste to frontmost app"

![CleanShot 2023-07-06 at 06 40 03](https://github.com/biati-digital/alfred-calculate-anything/assets/1219228/a054c494-0ad0-492e-ae2f-ce3c9622ec57)

**Comment by yarub123** [comment]
@biati-digital thanks, yeah I already have that checked. I knew about that one, but was trippin why isn't wasn't pasting regular calculations. No worries I ended up finding a soulver workflow last night after making this post and it solved the issue. ✌️
