### ISSUE TITLE
Workflow stops Alfred from working

### ISSUE THREAD

**Issue by Runnerbeen23** [biati-digital/alfred-calculate-anything#124]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Before creating an issue make sure you are using the latest version, you can find the latest version in the [releases page](https://github.com/biati-digital/alfred-calculate-anything/releases)

Yes

**Describe the bug**

I have downloaded the latest version of the workflow. I changed a couple of the options: time zone to Europe/London and VAT rate to 20% and when I then go to Use Alfred when I type ANYTHING in it just throws up an error message, please see attached 
<img width="535" alt="SCR-20230708-mdsk" src="https://github.com/biati-digital/alfred-calculate-anything/assets/138985791/4091898d-b83f-48f3-ad67-5a0a4a807347">

**To Reproduce**
1. Open Alfred '...'
1. Type '...'
2. See error
Open Alfred
Type anything
See error

**Expected behavior**

Alfred to work!

**Debug Output**
![Debug](https://user-images.githubusercontent.com/1219228/82741985-23988800-9d1e-11ea-84d0-151b9bd1db09.png "Debug")

Please enable debug (see image) open Alfred and type the conversion that it's not working, you will see that the debug window is populated with a lot of text, please paste that text in here.

**System information:**
 - OS: [e.g. Mac OS 10.15.15]
 - Alfred Version [e.g. 4]
- PHP Version - To find out the version open the Terminal.app and type: **php -v**

**Additional context**

**Comment by biati-digital** [comment]
Duplicate https://github.com/biati-digital/alfred-calculate-anything/issues/114#issuecomment-1533339292

You need to install the dependencies, please check the Readme.
