### ISSUE TITLE
Currency not working, failed cURL rates update call to fixer.io 

### ISSUE THREAD

**Issue by andrea-ww** [biati-digital/alfred-calculate-anything#126]
When testing, add an API key for fixer.io 

**To Reproduce**
1. Open Alfred '...'
1. Type '1 USD to 1 PHP'
2. See error

**Expected behavior**
Currencies would work during conversion

**Debug Output**
// Removed access key

[13:18:06.061] Calculate Anything[Script Filter] CURL FAILED: request to http://data.fixer.io/api/latest?access_key=<HERE>
<HERE>&format=1 failed, error was URL rejected: Malformed input to a URL functionCURL FAILED: request to https://api.apilayer.com/fixer/latest failed, error was Failed sending HTTP request{"items":[{"title":"Updating rates...","valid":false,"arg":""}],"rerun":0.2,"variables":{"rerun":true}}
[13:18:06.062] ERROR: Calculate Anything[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
CURL FAILED: request to http://data.fixer.io/api/latest?access_key=<HERE>
<HERE>&format=1 failed, error was URL rejected: Malformed input to a URL functionCURL FAILED: request to https://api.apilayer.com/fixer/latest failed, error was Failed sending HTTP request{"items":[{"title":"Updating rates...","valid":false,"arg":""}],"rerun":0.2,"variables":{"rerun":true}}

**System information:**
 - OS: Mac OS 13.4.1
 - Alfred Version 5
- PHP Version PHP 8.2.8

**Comment by derekbunch** [comment]
I think i am also experiencing this issue. Any chance a workaround has been found?

**Comment by biati-digital** [comment]
I totally missed this issue, @andrea-ww  is this error only happening with fixer? if you remove the API key to use the other service does it work?

@derekbunch you need to post your debug output and provide more information to be able to help. Please check all the provided info in the issue @andrea-ww created and provide the same.

**Comment by derekbunch** [comment]
My bad, my issue was just outdated php. Thanks!

**Comment by biati-digital** [comment]
@derekbunch  No problem, thank's for letting me know.
