### ISSUE TITLE
oz & ml conversion?

### ISSUE THREAD

**Issue by realliyifei** [biati-digital/alfred-calculate-anything#13]
Covert oz to ml, and vice versa?

<img width="558" alt="image" src="https://user-images.githubusercontent.com/32441766/93876937-393caf00-fd0a-11ea-8e9b-2a6736f1c294.png">

**Comment by biati-digital** [comment]
Not possible, this workflow has oz as a weight unit as it uses the metric system and probably will never add support for fluid ounces
