### ISSUE TITLE
Currency conversion macOS Sonoma

### ISSUE THREAD

**Issue by gustavosaez** [biati-digital/alfred-calculate-anything#131]
![CleanShot 2023-09-26 — 15h55m49s](https://github.com/biati-digital/alfred-calculate-anything/assets/7749461/a7e75d5d-e487-4043-bc93-6e9dce7cb659)

**Comment by gustavosaez** [comment]
> ![CleanShot 2023-09-26 — 15h55m49s](https://user-images.githubusercontent.com/7749461/270766297-a7e75d5d-e487-4043-bc93-6e9dce7cb659.png)

I never set any API, is there in the code?

**Comment by aronpaljakab** [comment]
Happened for me on Ventura as well. I did not have any API access key set before either. Perhaps the Fixer "free tier" plan has changed, no more free calls just through registered API keys?

**Comment by biati-digital** [comment]
Please use the issue template to provide all the required info.

There are no API keys in the code, if you did not set an API key then the workflow uses the exchangerate.host API, not sure if they are changing something as some other users reported 403 errors a few days ago #130

**Comment by gustavosaez** [comment]
Sorry about the template. I'll look for a possible solution then.

**Comment by KingMob** [comment]
This just happened to me, btw.

`[00:42:21.752] Calculate Anything[Script Filter] {"items":[{"title":"You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]","valid":false,"arg":""}],"rerun":false,"variables":{"rerun":true}}`

**Comment by biati-digital** [comment]
Seems that exchangerate.host now requires an API key.

I won't be supporting this change, exchangerate.host was only supported to save the user the trouble of getting an API key, if you require a key then go with fixer.io API is way better.

In the readme is explained how to get a free API Key from fixer.io

exchangerate.host will be removed in a future update.

**Comment by biati-digital** [comment]
> @biati-digital Would it be possible to add support for [Open Exchange Rates](https://openexchangerates.org/signup/free)? fixer.io asks for an address, which I'd rather not provide 😕

Seems that openexchangerates also requires an API key so i can't see any benefit, you mention the address but for me it simply means more work, more support, update docs, etc. I would only consider a free service that do not require an API key otherwise use fixer.io create an account with fake data.

**Comment by biati-digital** [comment]
exchangeratehost has been removed in the latest version https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.3
