### ISSUE TITLE
Outdated Info Re Fixer.io in the Alfred Workflow Configuration (Since 4.0.3)

### ISSUE THREAD

**Issue by Stickyhavr** [biati-digital/alfred-calculate-anything#138]
In the workflow configuration page, under the box for Fixer API, it says 
"**Not mandatory**. By default you have access to
32 currencies, If you need access to more than
150 currencies you can add a free API key. It
takes less than a minute to get the key from
https:|/fixer.io."

I believe this is no longer true and currency conversion will not work without the API key, right? So it should probably say something like:

"In order to do currency conversions you must add a free API key. It
takes less than a minute to get the key from https:|/fixer.io."

**Comment by lucasrabiec** [comment]
I added the API key but the calculator stucks at "Updating rates..." after writing currency and it shows nothing at all.

**Comment by biati-digital** [comment]
The description has been updated in the latest update.
