### ISSUE TITLE
Currency conversion doesn't work at all

### ISSUE THREAD

**Issue by sadokx** [biati-digital/alfred-calculate-anything#139]
The currency conversion doesn't work at all. I even have a fixed API but it just won't work. 

Here's the debug error:
```
ERROR: Calculate Anything[Script Filter] JSON is missing expected keys; items, variables or rerunafter:
{"items":{"0":{"title":"The requested URL returned error: 401","valid":false,"arg":""},"rerun":false}}
```

![image](https://github.com/biati-digital/alfred-calculate-anything/assets/12555077/978ee025-80d5-4509-84b9-b355dd20146f)

**System information:**
 - OS: MacOS 12.6.7 (21G651)
 - Alfred Version 5
- PHP Version - PHP 8.1.11 (cli) (built: Sep 29 2022 20:02:53)

**Additional context**
I saw in the logs that even though i wrote 40usd, the query only shows 0usd (you can see it in the screenshot). Had to re-write 4usd.

**Comment by biati-digital** [comment]
Please use the correct issue template and follow all the steps

**Comment by ItsMrAD** [comment]
I am having the same issue while using the default settings, and all the dependencies are installed
