### ISSUE TITLE
Incorrect base value for several Volume Units

### ISSUE THREAD

**Issue by vehovsky** [biati-digital/alfred-calculate-anything#14]
**Describe the bug**
Incorrect volume conversions. (I did not check all, just few I was interested in)

Current base values:
"pt" => array("base" => "l", "conversion" => 0.56826125), //pint
"gal" => array("base" => "l", "conversion" => 4.405), //gallon
"qt" => array("base" => "l", "conversion" => 1.1365225), //quart

I believe those should be used:
"pt" => array("base" => "l", "conversion" => 0.473176473), //pint
"gal" => array("base" => "l", "conversion" => 3.78541178), //gallon
"qt" => array("base" => "l", "conversion" => 0.946352946), //quart

**Comment by biati-digital** [comment]
The values are not incorrect, there are different systems of measurement (metric, imperial) and there's different values for some units for example gallons https://www.thecalculatorsite.com/articles/units/us-gallons-imperial-gallons.php

**Comment by vehovsky** [comment]
Ahh that is unfortunate. Would be nice to choose the preferred system..

**Comment by biati-digital** [comment]
Yep, understandable, i tried to implement that a few months ago but it was a lot of work and required time that i did not have, hopefully in the future i find some free time to add this.
