### ISSUE TITLE
Fixer API key seems to be needed even for common currencies? And error not shown in Alfred

### ISSUE THREAD

**Issue by gingerbeardman** [biati-digital/alfred-calculate-anything#140]
**Are you using the latest version of the workflow?**

Yes, 4.0.5

**Have you installed the workflow dependencies?**

Yes

**Describe the bug**

Previously this was working for me but after updating to 4.0.5 (from 4.0.2) it stopped working for my usual currency conversions. After debugging using Alfred I saw that I now need to enter a Fixer API. Generally I request conversions from USD, JPY, EUR to GBP.

Previously in 4.0.2 the missing API KEY error would be shown in the Alfred window.

**To Reproduce**
1. Open alfred
2. Type '100 usd to gbp'
3. See error in log that Fixer API KEY is required
4. No error is shown in Alfred window

**Expected behavior**

- Fixer API key should not be needed for "32 currencies"
- Error should be shown in Alfred window

- If the app changed to deprecate the service whose API KEY I was using, then please tell me about it! It's such a waste of time to have to repair things like this. Prevent the app breaking!

**Debug Output**

```
[15:19:27.133] Calculate Anything[Script Filter] Queuing argument '00 usd to gbp'
[15:19:27.267] Calculate Anything[Script Filter] Script with argv '(null)' finished
[15:19:27.269] Calculate Anything[Script Filter] {"items":{"0":{"title":"You need to configure the API key for Fixer","valid":false,"arg":""},"rerun":false}}
[15:19:27.270] ERROR: Calculate Anything[Script Filter] JSON is missing expected keys; items, variables or rerunafter:
{"items":{"0":{"title":"You need to configure the API key for Fixer","valid":false,"arg":""},"rerun":false}}
```

Also note that the leading 1 of 100 is missing, so the argument is only '00 usd to gbp'

**System information:**
 - OS: 12.7
 - Alfred Version: 5.1.3
- PHP Version - To find out the version open the Terminal.app and type: 8.2.11

**Additional context**

![Screen shot 2023-10-12 at 15 19 20](https://github.com/biati-digital/alfred-calculate-anything/assets/49612/13249863-8151-4bea-8a82-17b9762acdef)

![Screen shot 2023-10-12 at 15 19 31](https://github.com/biati-digital/alfred-calculate-anything/assets/49612/92419ee9-1ae4-4759-8998-67b66a163f5b)

**Comment by biati-digital** [comment]
See the closed issues, this has been asked several times. You now need an API key
