### ISSUE TITLE
Forum link on Alfred Gallery page leads to wrong topic

### ISSUE THREAD

**Issue by gingerbeardman** [biati-digital/alfred-calculate-anything#141]
On this page
https://alfred.app/workflows/biatidigital/calculate-anything/

Forum link leads to 
https://www.alfredforum.com/topic/10231-faster-menu-search/

I'm not sure if there is a forum thread for Calculate Anything

**Comment by biati-digital** [comment]
Thank's for letting me know. Alfred's Team created that, I've no control over that page, images, description, links, etc.

**Comment by gingerbeardman** [comment]
Have reported it here: https://github.com/alfredapp/gallery-edits/issues/15
