### ISSUE TITLE
Found and solved currency conversion BUG

### ISSUE THREAD

**Issue by soloetra** [biati-digital/alfred-calculate-anything#143]
I found and fixed a BUG that prevents connecting with a fixer_apikey:

On file "currency.php"

Inside function "getConfiguredExchangeData()"

Change:
$old_api = "http://data.fixer.io/api/latest?access_key={$fixer_apikey}&format=1";

To:
$old_api = "http://data.fixer.io/api/latest?access_key=$fixer_apikey&format=1";

Bye

**Comment by biati-digital** [comment]
what? you just removed the curly braces?

**Comment by soloetra** [comment]
👌

**Comment by biati-digital** [comment]
but why do you think that the curly braces must be removed? it's exactly the same output.

![Captura de pantalla 2023-10-20 203115](https://github.com/biati-digital/alfred-calculate-anything/assets/1219228/b108b6fb-5f58-47e3-aa3c-edfccb29fbff)
