### ISSUE TITLE
The addition of the translation has failed.

### ISSUE THREAD

**Issue by tlerbao** [biati-digital/alfred-calculate-anything#144]
The translation file I added is zh_CN.php and zh_CN-keys.php. I have reloaded it, but I still can't select the newly added language in the language selection list. What could be the reason for this issue?

<img width="316" alt="CleanShot 2023-10-28 at 09 59 54@2x" src="https://github.com/biati-digital/alfred-calculate-anything/assets/20442232/dd250f2a-856d-4d73-9a64-fac62280ebe3">

**Comment by biati-digital** [comment]
It's not possible for the workflow to populate those options dynamically. You need to modify your workflow options to display the new language https://www.alfredapp.com/help/workflows/workflow-configuration/
