### ISSUE TITLE
backcompat.php removed but still sourced in process.php

### ISSUE THREAD

**Issue by liuslouis** [biati-digital/alfred-calculate-anything#147]
Thanks for this awesome workflow. 

`/workflow/lib/backcompat.php` was removed in v4.0.1. However it is still required in [`process.php`](https://github.com/biati-digital/alfred-calculate-anything/blob/4.0.5/process.php#L24). 

I also noticed that `backcompat.php` is included in [release 4.0.5](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.5) so the workflow works fine. 

Is the file necessary now? If not, please remove it from `process.php`.

**Comment by biati-digital** [comment]
Thank's for letting me know. process.php has been updated to remove backcompat.php in the latest version.
