### ISSUE TITLE
Please add support for the CNY alias RMB, for example "1 usd to rmb" 

### ISSUE THREAD

**Issue by iDvel** [biati-digital/alfred-calculate-anything#148]
RMB stands for Renminbi and is more widely used in everyday contexts. Spotlight also supports this abbreviation.
![2023-11-30-002031](https://github.com/biati-digital/alfred-calculate-anything/assets/14658234/301aaeac-e0d7-403c-924f-b6c08b5dd149)

**Comment by SuQiANQAQ** [comment]
cny 对于你来说很难吗？

**Comment by Rasmis** [comment]
You can do this locally by adding this line below line 236 in the file `lang/en_EN-keys.php`. You find the file by going to the Alfred Workflows, right clicking Calculate Anything, and choose “Open in Finder”. 

```php
'RMB' => 'CNY',
```

**Comment by biati-digital** [comment]
Added in 4.0.6
