### ISSUE TITLE
Feature Request: Config option to never output workflow result numbers with commas

### ISSUE THREAD

**Issue by joshdavenport** [biati-digital/alfred-calculate-anything#15]
Personally, use this workflow more often for creating numbers that I'm plugging into code. This means having to remove the commas often. Extremely minor inconvenience but nonetheless would be lovely to have a config option telling the workflow I explicitly never want commas.

A good example where the commas get in the way a bit is for grabbing seconds for length variables and configuration of systems: "1 hr in s", "2 hours in s", "1 day in s", "1 hr in ms"

**Comment by biati-digital** [comment]
There's a bug with that, it should give you the value with no format if you press command+enter, it's working fine with currency. i'll fix this this weekend.

**Comment by joshdavenport** [comment]
Ah, fantastic. Thank you. 

Happy to PR if you're able to give some pointers :)

**Comment by biati-digital** [comment]
The new update it's ready [2.0.4](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/2.0.4)
