### ISSUE TITLE
Allow aliasing php binary path

### ISSUE THREAD

**Issue by keturiosakys** [biati-digital/alfred-calculate-anything#151]
**Are you using the latest version of the workflow?**

Using the latest version

**Have you installed the workflow dependencies?**

Dependencies are installed using `asdf` (for version management of different language runtimes/compilers)

**Describe the bug (config feature request)**

Currently the workflow requires the `php` binary to be in `/usr/bin` path which is an SIP protected path. Meaning if I would need to install the `php` dependency I would need to disable system protection for my laptop. I have `php` installed under a different path `~/.asdf/shims/php` that I would love to alias so that workflow could discover.

**System information:**
 - OS: macOS 13.6.2
 - Alfred Version 5
- PHP Version - 8.3.0

**Comment by biati-digital** [comment]
Hi. The workflow does not handle anything related to the PHP binary, that's Alfred, you'll need to ask directly to the Alfred Team as there's nothing I can do about this.
