### ISSUE TITLE
Installed PHP folder problem

### ISSUE THREAD

**Issue by ngthanhbinh85** [biati-digital/alfred-calculate-anything#153]
I have installed PHP before using the following command in the Terminal: brew install shivammathur/php/php@8.0
Now I see that the installed folder of PHP is not at /usr/bin/php. Is there any way to change the language in the workflow setting?

**Comment by biati-digital** [comment]
Hi. The workflow does **NOT** handle anything related to the PHP binary, that's Alfred, if you need help with this topic please use the [Alfred forum](https://www.alfredforum.com/topic/13974-calculate-anything/#comments) and most likely a moderator will be able to help.
