### ISSUE TITLE
Change ExchangeRate converstion from fixer.io to OpenExchangeRates

### ISSUE THREAD

**Issue by mobilutz** [biati-digital/alfred-calculate-anything#159]
I just started using your awesome workflow and was a bit disappointed that for currency conversion I don't just need an API-Key from fixer.io, but fixer.io also needs my credit-card even for the free version. I don't feel comfortable to give away my credit-card details when it is not needed.

So going back to what was written here: 

>> @biati-digital Would it be possible to add support for [Open Exchange Rates](https://openexchangerates.org/signup/free)? fixer.io asks for an address, which I'd rather not provide 😕
> 
> Seems that openexchangerates also requires an API key so i can't see any benefit, you mention the address but for me it simply means more work, more support, update docs, etc. I would only consider a free service that do not require an API key otherwise use fixer.io create an account with fake data.

_Originally posted by @biati-digital in https://github.com/biati-digital/alfred-calculate-anything/issues/131#issuecomment-1739564892_

My suggestion would be, to move either completely away from fixer.io or allow [OpenExchangeRates](https://openexchangerates.org/) as well as another option.

I do know, that this means a lot of work, and I am very willing to help. I will look into the implementation and maybe see if I can provide a suggestion for moving completely to OpenExchangeRates. What would you say to this?

**[edit]** Here my PullRequest on this topic: https://github.com/biati-digital/alfred-calculate-anything/pull/160

**Comment by biati-digital** [comment]
Removing fixer.io it's not an option, you'll break the workflow for all the users that already have a fixer API key, basically all users. 

Like I mentioned before in another comment, adding more exchange rates services means just more work and support, over the years we've implemented multiple services and still fixer it's the one that keeps working without much changes.

If you want you openexchangerates you can implement it but the user should have the option to use fixer or openexchangerates, existing users should be able to update the workflow and keep using their fixer API key.
