### ISSUE TITLE
Not respecting (,) and period (.)

### ISSUE THREAD

**Issue by zenminimalist** [biati-digital/alfred-calculate-anything#17]
When I enter say 23,51 CHF ist interpretes it as 2351 instead of 23.51. Here in Germany 23,51 CHF = 23.51. Is there any way to fix this? 

I've installed the workflow version 2.04. 
I've also set it to base language de_DE, still no success.

**Comment by zenminimalist** [comment]
This is still an issue. Any way CA could pull the system setting or a configuration option to change this? Ideally one could set the decimal and thousand seperator.

**Comment by biati-digital** [comment]
There's no easy way to get that configuration, i haven't have the time to look at this as i'm currently busy but as soon as i've some free time i'll try to find a solution.

**Comment by zenminimalist** [comment]
> There's no easy way to get that configuration, i haven't have the time to look at this as i'm currently busy but as soon as i've some free time i'll try to find a solution.

Hey, no worries. Whenever you have. Just remarking that would be nice and to adapt it to the relevant locale. As you can see, I'm still using since version 2 : )

**Comment by nemeth-it** [comment]
Yes, I'm very cautious when entering decimal numbers, just because it doesn't understand that dot and coma a swapped in german. (decimal: coma, thousand-seperator: dot) Hope there will be some replace available in the future.

**Comment by zenminimalist** [comment]
Any word on this issue? Would be a great addition to v3.1 🙂

**Comment by markus1338** [comment]
Love the workflow, but the decimal delimiter is also an issue for me.
An option or any other way to change the decimal delimiter to , "comma" would be awesome😃

**Comment by mgl1** [comment]
Would be great if that could be implemented.
Especially since the output can already be set.
Thx for the great workflow.

**Comment by zenminimalist** [comment]
Guys, we need to start buying this dev some coffee to get this fix :)

**Comment by biati-digital** [comment]
@zenminimalist wait, are you telling me that some devs receive some kind of monetary appreciation for their work? never crossed my mind in this 3 years working on this workflow :)

Anyway, I keep working on the workflow till this day, the last update was just 18 days ago but I need to choose carefully what features/changes are added, I do not want to end up providing more support or spend more time fixing bugs that could be caused by a new feature as I've limited free time. I do not forget about this issue, It will be added when I've the time as this requires significant changes in the code, I'll probably play with it once Alfred 5 is out.

**Comment by arvidbjorkstrom** [comment]
I submitted a pull request to solve this: https://github.com/biati-digital/alfred-calculate-anything/pull/94

**Comment by biati-digital** [comment]
A new version was released [4.0.0](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.0). Please read the release to see what's new.

The workflow includes new options to choose the decimal separator and is able to understand queries that includes multiple formats like:

```
1,234.56 meters to km
1 234,56 meters to km
1.234.56 meters to km
```

To configure the workflow you can use the new Alfred 5 Workflow configuration window.

![config](https://user-images.githubusercontent.com/1219228/226150121-a938ce29-815b-455c-b03f-af236c489275.png)

**Comment by markus1338** [comment]
Thank you very much, that's awesome.
I just updated and it works perfectly🙏👍
Really appreciate the time you put into this.

Do you have something like a digital coffee tip jar? 😀

**Comment by biati-digital** [comment]
Hi @markus1338 i'm glad it's working, it took more time than i expected and a lot of code was changed but i hope it was worth it.

Any donation is appreciated, we have a Stripe link for donations [https://buy.stripe.com/9AQbK2gPC5o73Fm7sz](https://buy.stripe.com/9AQbK2gPC5o73Fm7sz) where you can define any amount you want.

**Comment by markus1338** [comment]
Thanks again, enjoy your coffee/ tea 😀

**Comment by biati-digital** [comment]
Thank you @markus1338 you have officially become the first person to donate to this workflow 🎉. 
Thank’s for the support.

**Comment by Ciebiada** [comment]
> Thank you @markus1338 you have officially become the first person to donate to this workflow 🎉. Thank’s for the support.

This is unbelievable. Let me join!

**Comment by biati-digital** [comment]
@Ciebiada thank you 🙏, you are officially the second person to donate to this workflow 🎉  hopefully more people join.
