### ISSUE TITLE
Convertion to RSD not working

### ISSUE THREAD

**Issue by tihomiro** [biati-digital/alfred-calculate-anything#20]
Hey there, nice plugin!

Wanted to report that conversion to RSD currency is not working for some reason.

`1 USD EUR` works fine, `1 USD RSD` doesn't.

**Comment by biati-digital** [comment]
I'm not able to replicate the error. Can you please try and update the Workflow?

![CleanShot 2021-04-12 at 20 39 14](https://user-images.githubusercontent.com/1219228/114484077-2bc81300-9bcf-11eb-9cd3-8c2dff26ca86.png)

**Comment by tihomiro** [comment]
Works fine after the update. Thanks
