### ISSUE TITLE
calculate configure  ERROR

### ISSUE THREAD

**Issue by augusl** [biati-digital/alfred-calculate-anything#21]
If you have a problem with the workflow please answer the following questions.

**Describe the bug**

calculate configure  ERROR

**To Reproduce**
1. Open Alfred '...'
1. Type '...'
2. See error

**Expected behavior**

**Debug Output**
![Debug](https://user-images.githubusercontent.com/1219228/82741985-23988800-9d1e-11ea-84d0-151b9bd1db09.png "Debug")

Please enable debug (see image) open Alfred and type the conversion that it's not working, you will see that the debug window is populated with a lot of text, please paste that text in here.

[17:59:11.238] Calculate Anything[Script Filter] Queuing argument '(null)'
[17:59:11.303] Calculate Anything[Script Filter] Script with argv '(null)' finished
[17:59:11.306] STDERR: Calculate Anything[Script Filter] PHP Notice:  Undefined variable: curr_name in /Users/xxx/Public/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1571C986-A554-48AB-B7BE-801131ED96B9/configure.php on line 29
[17:59:11.307] Calculate Anything[Script Filter] Notice: Undefined variable: curr_name in /Users/xxx/Public/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1571C986-A554-48AB-B7BE-801131ED96B9/configure.php on line 29
{"items": [{"title":"Set base language","subtitle":"Configure the base language: en_EN","valid":true,"arg":"language","match":"Set base language","autocomplete":null},{"title":"Add base currency","subtitle":"Set a base currency: USD","match":"Add base currency","autocomplete":"Add base currency","valid":true,"arg":"add_base_currency"},{"title":"Delete base currency","subtitle":"Delete configured base currency","match":"Delete base currency","autocomplete":"Delete base currency","valid":true,"arg":"delete_base_currency"},{"title":"Set currency locale","subtitle":"Used to give format to the value using your country format: en_US","match":"Set currency locale","autocomplete":"Set currency locale","valid":true,"arg":"locale_currency"},{"title":"Set Coinmarketcap API","subtitle":"Configure your coinmarketcap API Key: ","match":"Set Coinmarketcap API","autocomplete":"Set Coinmarketcap API","valid":true,"arg":"coinmarket_apikey"},{"title":"Set Fixer API","subtitle":"Configure your fixer API Key: ","match":"Set Fixer API","autocomplete":"Set Fixer API","valid":true,"arg":"fixer_apikey"},{"title":"Set System of Measurement","subtitle":"Define your system of measurement default to metric system: metric","match":"Set System of Measurement","autocomplete":"Set System of Measurement","valid":true,"arg":"measurement_system"},{"title":"Set VAT percentage","subtitle":"Configure your default VAT percentage: 16%","match":"Set VAT percentage","autocomplete":"Set VAT percentage","valid":true,"arg":"vat_percentage"},{"title":"Set base timezone","subtitle":"Base time zone to calculate dates in your time: America\/Los_Angeles","match":"Set base timezone","autocomplete":"Set base timezone","valid":true,"arg":"time_zone"},{"title":"Add date format","subtitle":"Add date format","match":"Add date format","autocomplete":"Add date format","valid":true,"arg":"add_time_zone"},{"title":"Delete date format","subtitle":"Delete configured date format","match":"Delete date format","autocomplete":"Delete date format","valid":true,"arg":"delete_time_zone"},{"title":"Set base pixels","subtitle":"Configure the base pixels for font calculations: 16px","match":"Set base pixels","autocomplete":"Set base pixels","valid":true,"arg":"base_pixels"}] }
[17:59:11.308] ERROR: Calculate Anything[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Notice: Undefined variable: curr_name in /Users/xxx/Public/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1571C986-A554-48AB-B7BE-801131ED96B9/configure.php on line 29
{"items": [{"title":"Set base language","subtitle":"Configure the base language: 

**System information:**
 - OS: [e.g. Mac OS 10.15.15]
 - Alfred Version [e.g. 4]
- PHP Version - To find out the version open the Terminal.app and type: **php -v**
OS:11.2.3 (20D91)
Alfred:4.3.2
PHP:7.4.16

**Additional context**

**Comment by mihailtugushev** [comment]
Same :(

**Comment by biati-digital** [comment]
This should be fixed in the latest version, please update the workflow.
