### ISSUE TITLE
Currency Conversion not working

### ISSUE THREAD

**Issue by yamyoume** [biati-digital/alfred-calculate-anything#22]
If you have a problem with the workflow please answer the following questions.

**Describe the bug**
I was getting a lot of errors and I mean a lot, After debugging on my own and comparing with my laptop on which the workflow works perfectly,  I noticed that the workflow uses MacOS own PHP which is version 7.3.11 where I have brew PHP installed and currently have 7.4.14, anyway I noticed I had a php.ini file in /etc on my computer and not on my laptop, so I deleted it and it got rid of so many errors, but still currency conversion is throwing an error:

**To Reproduce**
1. Open Alfred '...'
1. Type '100 euros to dollars'
2. See error

**Expected behavior**
shows the price in usd

**Debug Output**
![Debug](https://user-images.githubusercontent.com/1219228/82741985-23988800-9d1e-11ea-84d0-151b9bd1db09.png "Debug")
```
[15:12:19.834] Logging Stopped.
[15:12:25.919] Logging Started...
[15:12:32.097] Calculate Anything[Script Filter] Queuing argument '00 euros to dollars'
[15:12:32.163] Calculate Anything[Script Filter] Script with argv '(null)' finished
[15:12:32.163] Calculate Anything[Script Filter] Warning: Division by zero in /Users/yamantarakji/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AC90BED8-9A7B-4593-98BB-EE8B929141F6/workflow/tools/currency.php on line 387
{"items": [{"title":".USD","subtitle":"1EUR = 0.00USD","arg":".","icon":{"path":"flags\/USD.png"},"mods":{"cmd":{"valid":true,"arg":0,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":0,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}}] }
[15:12:32.164] ERROR: Calculate Anything[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Warning: Division by zero in /Users/yamantarakji/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AC90BED8-9A7B-4593-98BB-EE8B929141F6/workflow/tools/currency.php on line 387
{"items": [{"title":".USD","subtitle":"1EUR = 0.00USD","arg":".","icon":{"path":"flags\/USD.png"},"mods":{"cmd":{"valid":true,"arg":0,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":0,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}}] }
```

Please enable debug (see image) open Alfred and type the conversion that it's not working, you will see that the debug window is populated with a lot of text, please paste that text in here.

**System information:**
 - OS: [e.g. Mac OS 10.15.15]
 - Alfred Version [e.g. 4]
- PHP Version - To find out the version open the Terminal.app and type: **php -v**

MacOS: 10.15.7
Alfred:  4.3.2
PHP 7.4.14 (brew) and 7.3.11 (macos) (which is what the workflow is using)

**Additional context**

**Comment by tjkohli** [comment]
+1

**Comment by yamyoume** [comment]
> +1

are you having the same issue?

**Comment by grovolis** [comment]
Having the same issue, currency conversion is always 0.

**Comment by Cygnusfear** [comment]
+1 same issue

recently installed pyenv and new python version

**Comment by comdr-chocchip** [comment]
+1

**Comment by chrisid** [comment]
Adding a fixer API key fixed it for me. [https://github.com/biati-digital/alfred-calculate-anything#currency-options](https://github.com/biati-digital/alfred-calculate-anything#currency-options)

**Comment by grovolis** [comment]
> Adding a fixer API key fixed it for me. https://github.com/biati-digital/alfred-calculate-anything#currency-options

Can confirm, worked for me too

**Comment by mr-pennyworth** [comment]
This is because exchangeratesapi.io now requires an `access_key`.

For more info: https://github.com/exchangeratesapi/exchangeratesapi/issues/117
Alternative (from the above link): https://api.exchangerate.host/latest

Here's a quick and dirty PR: https://github.com/biati-digital/alfred-calculate-anything/pull/23

**Comment by jerryyang0611** [comment]
> > Adding a fixer API key fixed it for me. https://github.com/biati-digital/alfred-calculate-anything#currency-options
> 
> Can confirm, worked for me too

How do I set the API key after getting my API secret key?
Sorry for asking this dumb question... but I kinda struggled to find it. 
I've tried to paste my API secret key here but doesn't seem to work...

![image](https://user-images.githubusercontent.com/45359868/114436267-b6bd0380-9bf7-11eb-9fe5-b68744a6e722.png)

Pls help :(

**Comment by biati-digital** [comment]
This should be fixed in the latest version, please update the workflow and give it a try.

**Comment by yamyoume** [comment]
- I could have sworn that I tried putting in the "Fixer API" didn't help but lo and behold I tried it now and it works (with the old version).
- as stated by the beloved developer with the new update, the built-in currency conversion works (with/without the "Fixer API")
issue closed, thank you and goodbye
