### ISSUE TITLE
Feature Request: Data transfer (megabytes, gigabytes, bits, etc)

### ISSUE THREAD

**Issue by luckman212** [biati-digital/alfred-calculate-anything#24]
Hi @biati-digital 
Nice looking plugin!
I didn't see any mention of it in the README, just wondering if there is any support for conversions of data transfer: MB/GB/TB etc?

**Comment by biati-digital** [comment]
No support for now but that should be easy to implement.

I'll keep it in mind for the next update.

**Comment by biati-digital** [comment]
Added in the latest update [v3](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/3.0.0) please checkout the README for more information

**Comment by solidgonk** [comment]
I think this might been some tweaking. The update introduced 'bits' alongside the other 'byte' measures, but they're not a converting properly. 

'1 megabit' (Mbit) is 1 million bits (b), which is 125000 bytes (or 0.125 MB) according to the common reference [1] I use for data. The workflow doesn't handle Mbits or bytes, but if I try '1000000 bit in mb', I get '1,024MB', which is not correct.

I recognise that a byte doesn't always equal 8 bits, but it's a good reference point when I'm reading through various technical docs.

Assuming it doesn't overcomplicate the workflow (noting that there's syntax to take into consideration with Mb vs MB), it would be great to see this implemented. Happy to do any testing too.

[1] https://www.gbmb.org/mbit-to-bytes
