### ISSUE TITLE
Featured Request: (US-Gallon and Fluid Ounces)

### ISSUE THREAD

**Issue by yamyoume** [biati-digital/alfred-calculate-anything#25]
This is not an issue, I just didn't know where to go for a request on the workflow
can we have US-Gallon and Fluid Ounces in the Volume conversions 
Thanks

**Comment by biati-digital** [comment]
Noted, I'll see what I can do.

**Comment by biati-digital** [comment]
Added in the latest update [v3](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/3.0.0) please checkout the README for more information

**Comment by yamyoume** [comment]
Nice job, 
just a few notes though, I think internally the numbers are being converted to liters and then back to us metric or something because 
if I put
"1 gal to floz" it's giving 128.000067 floz which should be only 128
![image](https://user-images.githubusercontent.com/31030392/116359260-7642b580-a7b3-11eb-8b7a-cf0987e4c670.png)
"64 floz to us gal" it's giving 0.49 usgal which should be 0.5  
![image](https://user-images.githubusercontent.com/31030392/116359288-7cd12d00-a7b3-11eb-8007-4fc69f98ffd1.png)

one last thing: 
qt or quart should be in both US Metric and UK or whatever because 1 us-qt should equal 32 us-floz
it's fair to note that other calculators/converters don't accommodate us-qt
![image](https://user-images.githubusercontent.com/31030392/116359772-0da80880-a7b4-11eb-8c88-a2760eff16eb.png)

other workflow  https://github.com/aviaryan/alfred-clc
![image](https://user-images.githubusercontent.com/31030392/116359847-23b5c900-a7b4-11eb-98a0-aa6c92e677cd.png)
![image](https://user-images.githubusercontent.com/31030392/116359872-29abaa00-a7b4-11eb-93b4-38ffde90a8fa.png)

**Comment by biati-digital** [comment]
Thank's for letting me know, yes there were a few things I wanted to change in the units to display results similar to other solutions but ran out of time, sadly I've to get back to work, it's a shame because I was having a good time working on the workflow and Alfred.

The examples help a lot, when I've some free time I'll take a look at the Conversion library and make the necessary changes. If you find anything else please let me know.

**Comment by biati-digital** [comment]
Hi, had to fix some bugs and decided to adjust this, please try it in the latest version https://github.com/biati-digital/alfred-calculate-anything/releases/tag/3.0.1

![CleanShot 2021-04-28 at 23 20 35](https://user-images.githubusercontent.com/1219228/116502153-5d500800-a878-11eb-9e30-5ac04e7084dd.png)

**Comment by yamyoume** [comment]
This one is correct
![image](https://user-images.githubusercontent.com/31030392/116516178-2252d200-a882-11eb-9055-d098e4fabb49.png)

buf if you try the other way around

![image](https://user-images.githubusercontent.com/31030392/116516210-2f6fc100-a882-11eb-9d42-bc781e691056.png)

![image](https://user-images.githubusercontent.com/31030392/116516267-43b3be00-a882-11eb-9043-c2adbb1c09a9.png)

**Comment by biati-digital** [comment]
Thank's for letting me know, I've fixed this issue, I'll try to release an update this weekend.

![CleanShot 2021-04-29 at 04 46 34](https://user-images.githubusercontent.com/1219228/116532569-0103dd00-a8a6-11eb-92ac-bd1b7e8c0dd9.png)

![CleanShot 2021-04-29 at 04 47 07](https://user-images.githubusercontent.com/1219228/116532576-02cda080-a8a6-11eb-9cef-a2dfa12eb78b.png)

**Comment by biati-digital** [comment]
Please try the latest update https://github.com/biati-digital/alfred-calculate-anything/releases/tag/3.0.2

**Comment by yamyoume** [comment]
Thank you, I think now everything is working perfectly 
amazing work
