### ISSUE TITLE
Incorrect Time Unit Conversion

### ISSUE THREAD

**Issue by jerryyang0611** [biati-digital/alfred-calculate-anything#27]
The month-to-week unit conversion seems to produce an incorrect result. 
E.g.
![image](https://user-images.githubusercontent.com/45359868/115199775-21090300-a126-11eb-99e7-f1b8b777a577.png)
![image](https://user-images.githubusercontent.com/45359868/115200005-5ca3cd00-a126-11eb-90a6-84c0f9632077.png)

**Comment by biati-digital** [comment]
Fixed in the latest update [v3](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/3.0.0)
