### ISSUE TITLE
Cannot lead conversions with period:  ".250 in to mm" instead of "0.250 in to mm"

### ISSUE THREAD

**Issue by khaoskosmos** [biati-digital/alfred-calculate-anything#3]
This is easy to change by adding a script filter for "." and setting the script to:

php ./process.php "0.{query}"

![Screen Shot 2020-03-11 at 6 51 23 PM](https://user-images.githubusercontent.com/57903341/76471573-63133180-63c9-11ea-90a7-8aff6ef16da5.png)

![Screen Shot 2020-03-11 at 6 46 19 PM](https://user-images.githubusercontent.com/57903341/76471481-26dfd100-63c9-11ea-99cc-a35c8608d604.png)

**Comment by biati-digital** [comment]
mmmm, yes that's how you modify the workflow to allow 0. but in alfred you will have to use it like **0.250 in to mm** 

To be able to use **.250 in to mm** it will need some changes, but try it and let me know if it works.

**Comment by khaoskosmos** [comment]
It looks like it work to me, unless I'm missing something:

![Screen Shot 2020-03-11 at 8 03 59 PM](https://user-images.githubusercontent.com/57903341/76474967-c4d89900-63d3-11ea-87a5-32b25509a692.png)

**Comment by biati-digital** [comment]
Well, the conversion seems to be done correctly but the decimals are not displayed correctly, it should only display 6.35. Are you using the latest version?

**Comment by khaoskosmos** [comment]
I was messing with the PHP files. I'd like to maintain the significant figures from the entered input, but it looks like $from_amount looses trailing zeros. I have an ugly way for "in to mm" and "mm to in" as I use those often.

![Screen Shot 2020-03-12 at 5 54 41 AM](https://user-images.githubusercontent.com/57903341/76509611-b23b7f80-6426-11ea-9269-db4a7fa250f2.png)

**Comment by biati-digital** [comment]
Hi, version 2.0.0 is out, if you have time please try it.
