### ISSUE TITLE
Feature Request: Support for more cryptocurrencies

### ISSUE THREAD

**Issue by LewisLebentz** [biati-digital/alfred-calculate-anything#30]
Please could we get support for more cryptocurrencies than the 100 hardcoded?

The API appears to allow up to 5000 to be requested in one request. Could it be set to dynamically support the top 1000 say? Or does Alfred require a hardcoded list to know to call this workflow?

If so, is it possible to maybe cache the top 1k daily for example and reference that list?

I'd be happy to sacrifice some ease of use and type something else to tell it I want to look for a non-hardcoded currency, if that would make it possible.

**Comment by biati-digital** [comment]
It does require a list to know that the query is about cryptocurrencies. The workflow could easily build the list out of the downloaded rates.json (it will require some small changes). 

The current implementation of the coinmarketcap API only returns 100 rates (by default), having 5000 or even 1000 cryptocurrencies will have an impact in performance as every time the user types it has to check if the query matches with a cryptocurrency.

The workflow already caches the response so there will be no difference.

If you are referring to a "keyword" I'm not agains it, probably will not be included by default as the idea of this workflow was to no use "keywords" but can be explained in the docs how to create the keyword.

That being said, I'll submit a big update today so I can not check this now, I've invested several days in the update and I've to get back to work. I'll mark this as a feature request and leave it open.

**Comment by biati-digital** [comment]
The number of cryptocurrencies has been incremented to 5,000 and also you can now define custom cryptocurrencies such as "sats". Please read the Readme for more information
