### ISSUE TITLE
currency calculation  bug

### ISSUE THREAD

**Issue by lronking** [biati-digital/alfred-calculate-anything#33]
**Describe the bug**
It doesn't work when I wanted to do some calculations about currency.

**To Reproduce**
1. Open Alfred
1. Type '100 USD to eur'
![iShot2021-04-28 22 45 25](https://user-images.githubusercontent.com/23070757/116424098-d1d47800-a873-11eb-8e6f-acb4607bbdcc.png)
2. See error

**Expected behavior**
I want to get correct answer.

**Debug Output**
This is Alfred workflow debug ERROR tracking:
```
[22:38:24.407] ERROR: Calculate Anything[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Warning: mkdir(): No such file or directory in /Users/duke/Downloads/Alfred setting/Alfred.alfredpreferences/workflows/user.workflow.981CDA56-3355-4457-BC3C-D0E828B804A6/alfred/Alfred.php on line 358

Warning: file_put_contents(/Users/duke/Library/Application Support/Alfred/Workflow Data/com.alfred.calculateanything/cache/exchangeratehost/rates.json): failed to open stream: No such file or directory in /Users/duke/Downloads/Alfred setting/Alfred.alfredpreferences/workflows/user.workflow.981CDA56-3355-4457-BC3C-D0E828B804A6/workflow/tools/currency.php on line 606
{"items":[{"title":"82.83 EUR","subtitle":"1 USD = 0.83 EUR","arg":"82.83","icon":{"path":"assets\/flags\/EUR.png"},"mods":{"cmd":{"valid":true,"arg":82.83,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":0.83,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}}]}
```
**System information:**
macOS 11.3
Alfred 4.3.4
PHP 7.3.24

Besides, I try to delete formal ca-v3 and re-import newly downloaded ca-v3.alfredworkflow. It doesn't work.

**Comment by jerryyang0611** [comment]
get rid of 's' and you would be able to get the result :)

**Comment by lronking** [comment]
this bug has a method to fix.
#31

**Comment by biati-digital** [comment]
is `eurs` something people use often? I can include it in the keywords.

**Comment by lronking** [comment]
maybe, i am not very sure. But seemingly people only add 's' at the end of 'eurs'?.....
we don't add 's' at usd, jpy or cny.

**Comment by biati-digital** [comment]
I'll add it just in case, the workflow already handles misspelled words and some common words so this is a really small change.
