### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by trankien386** [biati-digital/alfred-calculate-anything#39]
**Describe the bug**
Conversion is simply not working. Try to type `100$` or `1 hour to seconds` and it only shows `Search Google for...`

**To Reproduce**
Steps to reproduce the behaviour:
1. Trigger Alfred
2. Type `100$`
3. See errors

**Expected behaviour**
It should convert 100$ to my base currency in the line below.

**Debug Output**
![Debug](https://user-images.githubusercontent.com/61229079/120111746-5b41d780-c19d-11eb-8e4d-deaa659ba738.PNG "Debug")

**System information:**

 - OS: macOS 11.2.1
 - Alfred Version: 4.3.4 [1229]
- PHP Version - 7.3.24 <img width="738" alt="Screen Shot 2021-05-30 at 23 23 12" src="https://user-images.githubusercontent.com/61229079/120111955-110d2600-c19e-11eb-8d6e-c2b3d92d107c.PNG">

**Additional context**
About 10 days ago when I installed this workflow, it worked well. Today I try to use it but it turns out to be broken somehow.
I already reinstalled this workflow by downloading the latest version from Release page but it didn't fix the issue.

**Comment by biati-digital** [comment]
The error message says that it's not able to connect to the rates API site or even the Github site to check for updates.  This could be caused by firewall rules, an app to block connections like little snitch, etc.

**Comment by trankien386** [comment]
Thank you! I could have thought of that.
After trying several feasible solutions, such as turning Firewall off and on again, adding Alfred to Firewall allowed list, restarting Alfred, trying steps at https://github.com/biati-digital/alfred-calculate-anything/issues/32#issuecomment-829534648, it's working again. 😋

Firewall didn't seem to affect anything. I think restarting Alfred and performing steps at https://github.com/biati-digital/alfred-calculate-anything/issues/32#issuecomment-829534648 fixes all issues.

**Comment by trankien386** [comment]
One thing I've noticed is that typing `30$` doesn't work. `30dollar` and `30 $`  work. Debug doesn't show any error. It's just doesn't trigger conversion. Is this expected behaviour?
![dollarconversion](https://user-images.githubusercontent.com/61229079/120163128-5f183d00-c223-11eb-8f04-342b54ba373a.png)
