### ISSUE TITLE
Cryptocurrency Support

### ISSUE THREAD

**Issue by LewisLebentz** [biati-digital/alfred-calculate-anything#4]
Great workflow, one of the best I've seen so far - good job!

Was just wondering if there's a chance you could add support for cryptocurrencies too? Looks like Fixer.io only supports Bitcoin.

CoinMarketCap seems to have a free API where we could grab our own keys:
https://coinmarketcap.com/api/

**Comment by LewisLebentz** [comment]
Looks like you haven't added support for BTC into the workflow either, looks like it should be a one liner... not sure where though!

**Comment by biati-digital** [comment]
Thanks, I'm glad you like this workflow. Cryptocurrencies are already in the works. I'll let you know when it's ready.

**Comment by biati-digital** [comment]
Version 2.0.0 is out with Cryptocurrency support.
