### ISSUE TITLE
Vat not accurate

### ISSUE THREAD

**Issue by yamyoume** [biati-digital/alfred-calculate-anything#40]
If you have a problem with the workflow please answer the following questions.

**Describe the bug**
Vat is not accurate

**To Reproduce**
ca Set Vat was set to 7.75
Vat 100 produce 
VAT of 100 = 7  should be 7.75
100 plus VAT = 107, should be 107.75
100 minus VAT = 58.82 This doesn't make sense 

**Expected behavior**

**Debug Output**
![Debug](https://user-images.githubusercontent.com/1219228/82741985-23988800-9d1e-11ea-84d0-151b9bd1db09.png "Debug")

Please enable debug (see image) open Alfred and type the conversion that it's not working, you will see that the debug window is populated with a lot of text, please paste that text in here.

**System information:**
 - OS: 10.15.7
 - Alfred Version 4.3.4
- PHP Version 8.0.6

**Additional context**
![image](https://user-images.githubusercontent.com/31030392/123559898-c4dce380-d753-11eb-9386-5f8a6144ccf9.png)

![image](https://user-images.githubusercontent.com/31030392/123559953-12595080-d754-11eb-9332-0356c30b2967.png)

**Comment by yamyoume** [comment]
I was able to correct the rounding by editing vat.php 
![image](https://user-images.githubusercontent.com/31030392/123560270-14bcaa00-d756-11eb-86a9-525a911b8202.png)

**Comment by yamyoume** [comment]
I found another thing 😅
I'm calculating this vat 
![image](https://user-images.githubusercontent.com/31030392/123560654-7bdb5e00-d758-11eb-86b9-9336773be54d.png)
so the rounded final answer should be $13.73
but with VAT 12.47 I'm getting $13.72
![image](https://user-images.githubusercontent.com/31030392/123560685-9f060d80-d758-11eb-8b4a-fc069d86adc0.png)

**Comment by yamyoume** [comment]
so I fixed the precision by doing this 
![image](https://user-images.githubusercontent.com/31030392/123736239-a101c680-d855-11eb-872a-52236821160b.png)

![image](https://user-images.githubusercontent.com/31030392/123736252-a52de400-d855-11eb-80fe-2a4e3384ff9b.png)

**Comment by yamyoume** [comment]
![image](https://user-images.githubusercontent.com/31030392/124351608-2ff14480-dbb0-11eb-8fb7-f93c36bd52a4.png)

I made {amount} minus VAT to equal the TTC thing
so with this, if you put vat 100, then 100 minus vat will give you the price of the product before the vat was added to it, so if you take that number and you use vat {that number} again then, {amount} plus VAT will give you the original number

![image](https://user-images.githubusercontent.com/31030392/124351580-10f2b280-dbb0-11eb-923d-ad5c00cdd32c.png)

![image](https://user-images.githubusercontent.com/31030392/124351590-1bad4780-dbb0-11eb-9ab9-25939448272b.png)

**Comment by yamyoume** [comment]
all the changes I have made were to the getVatOf function, it's located in ( ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C378AFE7-8701-4C25-B8B6-B6716AA3F957/workflow ) and here it is 
```
    public function getVatOf($amount)
    {
        $query = $amount;
        $percent = $this->percent;
        $processed = false;

        if (empty($query)) {
            return $this->output($processed);
        }

        // $percent = (int) $percent;
        $percent = (float) $percent;
        $amount = $this->cleanupNumber($query);

        $result = ($percent / 100) * $amount;
        $result = (fmod($result, 1) !== 0.00 ? bcdiv($result, 1, 3) : $result);

        if ($result && $result > 0) {
            $processed = true;
            $plusvat = $amount + $result;
            // $minusvat = $amount / ((float) "1.$percent");
            $minusvat = $amount/(1+($percent/100));
            $lang = $this->lang;

            $result = $this->formatNumber($result);
            $plusvat = $this->formatNumber($plusvat, -1, true);
            $minusvat = $this->formatNumber($minusvat, -1, true);
            $amount = $this->formatNumber($amount);

            $processed = [
                'result' => [
                    'title' => sprintf($lang['result'], $amount, $result),
                    'subtitle' => sprintf($lang['subtitle'], "{$percent}%"),
                    'value' => $result
                ],
                'plusvat' => [
                    'title' => sprintf($lang['plus'], $amount, $plusvat),
                    'subtitle' => sprintf($lang['subtitle'], "{$percent}%"),
                    'value' => $plusvat
                ],
                'minusvat' => [
                    'title' => sprintf($lang['minus'], $amount, $minusvat),
                    'subtitle' => sprintf($lang['minus_subtitle'], $amount, "{$percent}%"),
                    'value' => $minusvat
                ],
            ];
        }

        return $processed;
    }
```

**Comment by biati-digital** [comment]
Thank you @yamyoume i'll include this fix in the next update.

**Comment by biati-digital** [comment]
This has been fixed in the [latest version](https://github.com/biati-digital/alfred-calculate-anything/releases)

Again, thank you for your help.
