### ISSUE TITLE
Time not converting

### ISSUE THREAD

**Issue by vaidab** [biati-digital/alfred-calculate-anything#43]
Latest version of the code.
I'm using the time format: j F Y g:i a  and the timezone: Bucharest (3 hours difference from UTC).
"time 3pm" shows the date + "3:00 pm" ; under it there's another format showing that it's in 3 hours.
"time 3pm utc" shows the same date ("3:00 pm") yet under it it shows 6 hours.
"time utc" wrongly displays my current timezone's time (not the UTC time).

Any idea what is happening?

**Comment by biati-digital** [comment]
Please use the bug report template so you can provide the required information.
