### ISSUE TITLE
Feature Request: Modulo operation

### ISSUE THREAD

**Issue by ErikMinekus** [biati-digital/alfred-calculate-anything#44]
`%` currently only calculates the percentage, but in programming it's common to use it to calculate the remainder of a division, for example `5 % 2 = 1`.

I would like to see the workflow return both.

**Comment by biati-digital** [comment]
I think this can cause confusion to users that are not developers as they will not understand that result. The workflow  uses `%` to calculate percentages so for now this is not something i'm planning to implement.
