### ISSUE TITLE
Alfred unable to run task after typing 'ca'

### ISSUE THREAD

**Issue by FraserEmbrey** [biati-digital/alfred-calculate-anything#45]
If you have a problem with the workflow please answer the following questions.

**Describe the bug**
I installed calculate anything to Alfred 4 on my M1 MacBook Pro. The 

**To Reproduce**
1. Open Alfred
1. Type 'ca'
2. See error window with 
![Screenshot](https://user-images.githubusercontent.com/7635426/126759964-17ab1dd0-7eb7-481d-9710-1d2434206461.jpg)

> Reason: launch path not accessible
> 
> It's likely that the folder required to run this task has somehow been deleted, perhaps syncing?
> 
> This error isn't that serious, just try again :)
> 
> Related Workflow Info...
> Name: 'Calculate Anything'
> Folder:/Users/frsr/.config/alfred/Alfred.alfredpreferences/workflows/user.workflow.5D2E604F-EBE9-4000-8297-5D37A49326F5

**Expected behavior**
Alfred not to freak out and to let me set language as described in README.

**Debug Output**
[10:01:54.290] Logging Started...
[10:01:56.882] Calculate Anything[Script Filter] Queuing argument ''

**System information:**
 - OS: macOS 12.0 b3
 - Alfred Version: 4
- PHP Version: 8.0.8

**Additional context**
I didn't have php installed but I downloaded it with homebrew and tried again without any change.

**Comment by biati-digital** [comment]
As mentioned in the Alfred forum this is probably not a workflow problem. If you are using a beta there's nothing we can do. That error is displayed by Alfred itself, the workflow does not even runs as you can see in the debug output. I never install betas so can't replicate it.

**Comment by FraserEmbrey** [comment]
Ok thank you for your quick response.
