### ISSUE TITLE
Feature request: add support for knots and nautical miles

### ISSUE THREAD

**Issue by aism** [biati-digital/alfred-calculate-anything#47]
Hello there,

Please add support for knots and nautical miles.

**Comment by chrisparker787** [comment]
Seconded - knots and nautical miles would be really useful.

**Comment by biati-digital** [comment]
Knots was added in the latest version, for nautical miles please someone post all the units, i've limited time and probably won't spend it investigating this so any help is appreciated.

**Comment by biati-digital** [comment]
The latest version can be found in the releases page [https://github.com/biati-digital/alfred-calculate-anything/releases](https://github.com/biati-digital/alfred-calculate-anything/releases)

**Comment by IamYip** [comment]
I am on 3.5.0 and can't get nmi to work as conversion start or target. :(

**Comment by arvidbjorkstrom** [comment]
Somewhere `nmi` is being converted to nm. So the conversion becomes from/to nano meters instead of nautical miles. Researching further.

**Comment by arvidbjorkstrom** [comment]
Submitted pull request with fix
