### ISSUE TITLE
Time function is broken

### ISSUE THREAD

**Issue by alexsmedile** [biati-digital/alfred-calculate-anything#49]
Hi,

I'm not able to use "time" function. It does show up when I write "time" but quickly goes away when I add something else.

I have no other function linked to "time" keyword.

![image](https://user-images.githubusercontent.com/30530199/130053804-5dc06e1b-0e05-4e9e-8d00-2296f7c2822c.png)

My Config if can help is Mac M1.

**Comment by biati-digital** [comment]
Please follow the bug report template when creating a new issue
