### ISSUE TITLE
Unable to run task

### ISSUE THREAD

**Issue by themarcelwerner** [biati-digital/alfred-calculate-anything#51]
Hi,

since I upgraded to macOS Monterey I can not run your workflow anymore.
 
**Are you using the latest version of the workflow?**
Currently, I am using v.3.0.2

**Describe the bug**
When I type "ca" I got the following error message "Unable to run task". (Screenshot attached)

**To Reproduce**
1. Open Alfred '...'
1. Type 'ca'
2. See error

**Debug Output**
See attachment
![Screen Shot 2021-11-01 at 11 40 41](https://user-images.githubusercontent.com/82438990/139661567-512fdd17-9dfe-4290-9090-a22892c6c251.png)
![Screen Shot 2021-11-01 at 11 56 09](https://user-images.githubusercontent.com/82438990/139661569-47eb63f0-30f4-4777-95d4-36e067f2d477.png)

**System information:**
 - OS: macOS Monterey 12.0.1
 - Alfred Version 4.6

**Comment by biati-digital** [comment]
There's an open issue already

**Comment by maximilianigl** [comment]
I have the same problem and don't see a fitting open issue. There's one about currencies not converting, but this bug here just prevents anything from working.
Problem for me seems to be that php is in /usr/local/bin/php, not /usr/bin/php.

**Comment by maximilianigl** [comment]
FYI, got fixed with Alfred update. Still doesn't work, but now for a different reason.

**Comment by biati-digital** [comment]
Hi @maximilianigl glad it's working. that's already explained in the ReadMe, the Alfred Forum and the closed issues here.

**Comment by maximilianigl** [comment]
This issue is what came up in my search, so I assumed that it would for others as well and as there isn't any link to an existing issue or other information, I wanted to provide it here as well.
