### ISSUE TITLE
Converting currencies does not work

### ISSUE THREAD

**Issue by vosco88** [biati-digital/alfred-calculate-anything#52]
**Are you using the latest version of the workflow?**
Yes

**Describe the bug**
When trying to convert currencies calculate anything does not work, all I am getting are default searches. 

**To Reproduce**
1. Open Alfred '...'
1. Type '600 usd to eur'
2. See only the searches options

**Expected behavior**
Converted value is displayed

**Debug Output**
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/14372933/141865202-81b45e85-887e-4d9b-9f26-d38eb9ef6273.png">

ERROR: Calculate Anything[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Deprecated: Function money_format() is deprecated in /Users/janko/Documents/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D46C1DFA-AA24-4138-8DCA-E37022618D37/workflow/tools/currency.php on line 266

Deprecated: Function money_format() is deprecated in /Users/janko/Documents/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D46C1DFA-AA24-4138-8DCA-E37022618D37/workflow/tools/currency.php on line 269
{"items":[{"title":"105,53 EUR","subtitle":"1 USD = 0,88  EUR","arg":"105,53","icon":{"path":"assets\/flags\/EUR.png"},"mods":{"cmd":{"valid":true,"arg":10553,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":88,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}}]}

**System information:**
 - OS: Mac OS 12.0.1
 - Alfred Version 4.6
- PHP Version - 7.4.25

**Additional context**

**Comment by mihailtugushev** [comment]
same

**Comment by biati-digital** [comment]
Please try the latest version and let me know if it's working for you https://github.com/biati-digital/alfred-calculate-anything/releases

**Comment by vosco88** [comment]
It does work for me, thank you
