### ISSUE TITLE
Very very small issue with VAT

### ISSUE THREAD

**Issue by yamyoume** [biati-digital/alfred-calculate-anything#53]
I'm setting up a new Macbook Pro M1Pro
after installing the workflow I was testing everything and VAT wasn't working. 
Turns out that even that by default it's set to 16%, it didn't work, but after I hit `ca` and `set vat` it works as expected.
but if you have a fresh install the default 16% doesn't take effect

**Comment by biati-digital** [comment]
Thanks for letting me know, I'll take a look at this.

**Comment by biati-digital** [comment]
This has been fixed in the latest version
