### ISSUE TITLE
Base currency not converting cryptocurrencies properly

### ISSUE THREAD

**Issue by yoyoyojoe** [biati-digital/alfred-calculate-anything#56]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Yes. Current version installed is 3.1.1 (lasted updated Nov 1)

**Describe the bug**
When querying cryptocurrency, the conversion only occurs for USD. Other base currencies, in my case, all 1 BTC calculates to 0.00 in CNY, EUR, TWD.

**To Reproduce**
1. Open Alfred
2. Type 'ca add' and select ["Add base currency"]
3. Add any countries/currencies as desired, and press enter to save
3. Type '1btc'

**Expected behavior**
I expected the currency conversion / calculation to occur and show corresponding to the cryptocurrency entered (BTC, ETH, etc).

**Debug Output**
![image](https://user-images.githubusercontent.com/86270711/147148381-e687a046-abaf-4aa5-bb3f-5f5e6ac4920c.png)

Please enable debug (see image) open Alfred and type the conversion that it's not working, you will see that the debug window is populated with a lot of text, please paste that text in here.

**System information:**
 - OS: [Mac OS 12.1]
 - Alfred Version [Alfred 4.6.1]
- PHP Version: PHP 8.1.1 (cli) (built: Dec 17 2021 22:21:23) (NTS)

**Additional context**
A small oversight, but still a bug. However, you've created quite an amazing work flow / app! Congratulations and thank you!

**Comment by biati-digital** [comment]
Interesting, thank's for reporting this, i'll try to recreate it and fix it. 

I'm really glad you like this workflow.

**Comment by biati-digital** [comment]
mmmm... i'm not able to replicate it. can you please share the content of the debug pane?

![CleanShot 2021-12-22 at 19 58 38](https://user-images.githubusercontent.com/1219228/147176121-aae5603a-256c-49e3-874d-4a33f7325e5a.png)

**Comment by biati-digital** [comment]
Closing as no more info was provided
