### ISSUE TITLE
Fixer API Key breaking currency conversion

### ISSUE THREAD

**Issue by yoyoyojoe** [biati-digital/alfred-calculate-anything#57]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Yes. Current version installed is 3.1.1 (lasted updated Nov 1)

**Describe the bug**
There seems to be an issue converting currency after I entered the Fixer.io API Key. The conversion seemed fine without it.

**To Reproduce**
1. Open Alfred
2. Type 'ca set' and select ["Set Fixer API"]
3. Enter my Free Fixer API, and press enter to save
4. Type '100 usd'
5. See error

**Expected behavior**
I expected the currency conversion / calculation to occur. 

_Working with default setup:_

![image](https://user-images.githubusercontent.com/86270711/147149689-ae99e5ed-03f2-43dd-85c9-9d136691e652.png)

Note: This is not an issue for default conversion mechanism. 

_*****This only occurs when I enter have a Fixer API Key._

**Debug Output**

_Not working with API Key entered (with any currency)_

![image](https://user-images.githubusercontent.com/86270711/147149838-c38689a6-0c8e-4cbe-86bc-9298b586dc96.png)

![image](https://user-images.githubusercontent.com/86270711/147149955-953b7825-d513-4536-b4fe-651853b0c1fe.png)

Please enable debug (see image) open Alfred and type the conversion that it's not working, you will see that the debug window is populated with a lot of text, please paste that text in here.

**System information:**
 - OS: [Mac OS 12.1]
 - Alfred Version [Alfred 4.6.1]
- PHP Version: PHP 8.1.1 (cli) (built: Dec 17 2021 22:21:23) (NTS)

**Additional context**
You've created quite an amazing work flow / app, so I felt compelled to let you know a bug when I see one. 
It currently works for me with the default currencies. Congratulations and thank you!

**Comment by biati-digital** [comment]
You should try creating a new Fixer API Key, there's currently no error handling for API errors but if you see that it can be that the rate limit has been exceeded (happened to me last month and saw the exact same error) or your key has been disabled.

I'll improve this to display the errors returned by the API.

**Comment by biati-digital** [comment]
There's a new update that should display the errors returned by the Fixer API [https://github.com/biati-digital/alfred-calculate-anything/releases](https://github.com/biati-digital/alfred-calculate-anything/releases)

**Comment by yoyoyojoe** [comment]
Thank you. I set up the fixer API at first thinking it was needed. I've found the default currencies to be sufficient for now, but just wanted to let you know.
