### ISSUE TITLE
Question about decimal

### ISSUE THREAD

**Issue by max837381** [biati-digital/alfred-calculate-anything#59]
Would it be possible to have more decimal points in the currency output?

**Comment by trepechov** [comment]
Agree... For cryptocurrencies for sure 2 digits after the decimal are not enough

**Comment by biati-digital** [comment]
Sure, i'll add an option for this soon.

**Comment by biati-digital** [comment]
This was added the latest version [4.0.0](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.0). Please read the release to see what's new.
