### ISSUE TITLE
I can't make some units work

### ISSUE THREAD

**Issue by nmaxcom** [biati-digital/alfred-calculate-anything#6]
I'm not sure if this is user error; at the very least is a confusing workflow. Since I'm usually having trouble with pounds, I added this to my en_EN-keys.php
```php
'pound' => 'lb',
'pounds' => 'lb',
```

So, here are some inconsistencies IMO:

This works
![image](https://user-images.githubusercontent.com/8936090/82284467-5b5ba480-9999-11ea-95ac-b7a6cff5b89e.png)

But this doesn't
![image](https://user-images.githubusercontent.com/8936090/82284520-78907300-9999-11ea-9363-9ade0febca0b.png)

But it works this way after adding it to en_EN-keys.php
![image](https://user-images.githubusercontent.com/8936090/82284542-8b0aac80-9999-11ea-8a57-4189654ec0c9.png)

This one is about precision that anything else, but still.
![image](https://user-images.githubusercontent.com/8936090/82284619-b7bec400-9999-11ea-9b8d-22aa5849c43b.png)

Thanks for the effort

**Comment by biati-digital** [comment]
That's an error, I'll take a look next weekend

**Comment by biati-digital** [comment]
is this the part that is confusing for you? or there are other things that you consider confusing?

**Comment by nmaxcom** [comment]
Well, to be honest I haven't used it frequently enough to notice more things because I was a bit let down when the lb conversion didn't work. I'm aware it has more things to offer, I'll try to explore more.

The most confusing part is having one way conversions, e.g.: `kg to lb`, but not `lb to kg`.

**Comment by biati-digital** [comment]
Ahh ok, it does not have one way conversions, what you found it's simply an error, for example you can try

```
1 kg to oz
1 oz to kg

or

1 usd in yen
1 yen in usd

etc.
```

This update was a complete rewrite so there are probably some bugs. If you find another bug please let me know.

**Comment by biati-digital** [comment]
There's a new update (2.0.2) that fixes the errors you mention, please try it and let me know if it's working for you.

**Comment by nmaxcom** [comment]
Weird. I try to update using "Calculate check for updates" and I get this:
![image](https://user-images.githubusercontent.com/8936090/82847163-d4ed1880-9eec-11ea-87ce-8cda32f09190.png)

But when I go to Alfred Workflows it shows me I'm using the 2.0.1 version.

**Comment by biati-digital** [comment]
Sorry, I forgot to update the version of the GitHub plist file, please try again "Calculate check for updates"

**Comment by nmaxcom** [comment]
It works great now. Both the conversion from lb and the precision are working as expected.

I see in your commit you added pound and pounds, that's great. Would you mind adding **lbs** as a **lb** synonym?
Thanks!

**Comment by biati-digital** [comment]
Great, I'll add it in the next update :relaxed:
