### ISSUE TITLE
 Can't convert negative Fahrenheit to C 

### ISSUE THREAD

**Issue by GonzoTG** [biati-digital/alfred-calculate-anything#62]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?** - Yes, v3.3.0

**Describe the bug**
I tried converting the current temp -7 degrees Fahrenheit to Celcius and the workflow does not show any results. It appears that negative Fahrenheit conversions don't work.

**To Reproduce**
1. Open Alfred 
1. Type '-7 F in C'

**Expected behavior**
A temperature in Celcius

**Comment by biati-digital** [comment]
It's not possible right now, to bypass the mandatory Alfred "keyword", we used numbers from 0 to 9 as keywords, this allows the workflow to execute the queries like "Mac OS Spotlight", so the workflow will only process queries that start with a number (from 0 to 9), your query starts with a minus sign so it's not processed.

To allow negative numbers we'll have to duplicate the "scripts filters" in Alfred to process from -0 to -9, currently there's no plans to change that as this is the first time someone asks for this but i know this can be useful so i'll leave it open as a feature request.

**Comment by biati-digital** [comment]
This was added in the latest version [4.0.0](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.0). Please read the release to see what's new.
