### ISSUE TITLE
Add support to satoshis

### ISSUE THREAD

**Issue by AdamVyborny** [biati-digital/alfred-calculate-anything#66]
It would be nice if I can use `1000 sats` or `12345 sats to USD`. It should not be hard to implement because it should act same as BTC only if keyword is `sats` you divide number by hundred mils before conversion

**Comment by biati-digital** [comment]
The number of cryptocurrencies has been incremented to 5,000 and also you can now define custom cryptocurrencies such as "sats". Please read the Readme for more information

Get the latest version from the releases page https://github.com/biati-digital/alfred-calculate-anything/releases

![CleanShot 2022-06-05 at 22 55 35](https://user-images.githubusercontent.com/1219228/172092381-d8c04be0-9e8c-4131-b764-a92807edc639.png)

If you have problems please open a new issue

**Comment by yarub123** [comment]
@biati-digital Satoshis are still not working. Also the readme has nothing regarding it(?)

I checked the en_EN-keys.php file just to double check if it was in there. And it was satoshis as 'SAT'

Problem is every other currency works EXCEPT satoshis in this workflow lol.

**Comment by AdamVyborny** [comment]
@biati-digital @yarub123 Yeah, it stopped working after some updates.

**Comment by yarub123** [comment]
@AdamVyborny No worries. Thanks 🙏
