### ISSUE TITLE
AUD Currency trying to calculate as cryptocurrency

### ISSUE THREAD

**Issue by diva-D** [biati-digital/alfred-calculate-anything#70]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Yes - v3.4.0

**Describe the bug**
When trying to convert AUD (Australian Dollar) the workflow returns "The crypto currency is not available, check the docs."
![CleanShot 2022-06-10 at 10 27 46](https://user-images.githubusercontent.com/28694272/172956270-38fb6b7f-1687-419e-ba56-b8d22e1e9dc7.png)

**To Reproduce**
1. Open Alfred 
1. Type '1000 aud to nzd'
1. See error

**Expected behavior**
The outputs shows the converted amount. Like it does with USD
![CleanShot 2022-06-10 at 10 32 51](https://user-images.githubusercontent.com/28694272/172956186-ecdd662d-8af3-4ea6-9f43-8cd910577e78.png)

**Debug Output**
```
[10:34:58.723] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.75E71904-54E5-4F49-A5F0-1995AEB08C19%3E2679D5D4-9D36-4AD4-A1EE-59EACA36C6E9)] Queuing argument '000 aud to nzd'
[10:34:58.757] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.75E71904-54E5-4F49-A5F0-1995AEB08C19%3E2679D5D4-9D36-4AD4-A1EE-59EACA36C6E9)] Script with argv '(null)' finished
[10:34:58.758] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.75E71904-54E5-4F49-A5F0-1995AEB08C19%3E2679D5D4-9D36-4AD4-A1EE-59EACA36C6E9)] {"items":[{"title":"The crypto currency is not available, check the docs.","valid":false,"arg":""}]}
```

**System information:**
 - OS: Mac OS 12.4
 - Alfred Version: 4.6.6
- PHP Version: 8.1.5

**Additional context**
AUD shows in the currency list `ca list`
![CleanShot 2022-06-10 at 10 29 16](https://user-images.githubusercontent.com/28694272/172956613-00030d15-8c8c-4b0e-859e-57cf740fa139.png)

**Comment by victorchor2868** [comment]
Me too, also facing this issue. British Pound is also
<img width="706" alt="CleanShot 2022-06-12 at 14 22 59@2x" src="https://user-images.githubusercontent.com/87065622/173220025-f73fbf93-70b5-4de9-90df-e5510c805268.png">
<img width="706" alt="CleanShot 2022-06-12 at 14 22 48@2x" src="https://user-images.githubusercontent.com/87065622/173220031-2aaa53a8-92f7-49d3-8c5c-f25d933e4f36.png">

**Comment by berters** [comment]
Experiencing the same with GBP.

**Comment by biati-digital** [comment]
Hi, I'm aware of this, currently I'm having a lot of work so I'll take a look at this as soon as I've some free time.

**Comment by wangxiaoshi** [comment]
Same issue for Argentine Peso

**Comment by DANgerous25** [comment]
Same issue for me with Thai Bhat. It works if I convert from USD -> THB, but doesn't work for THB -> USD. I am pretty sure it was working before I upgraded. I also updated my fixer.io API key, didn't help.

Thank you for the awesome workflow, btw.

**Comment by tchlyah** [comment]
Same issue for AED, is there any workaround or should we rollback waiting for a fix ?

Thanks.

**Comment by biati-digital** [comment]
This issue should be fixed in the latest version 3.5.0 [view releases page](https://github.com/biati-digital/alfred-calculate-anything/releases)

**Comment by diva-D** [comment]
Can confirm it's working for me!

**Comment by DANgerous25** [comment]
Agree, fixed for me.
