### ISSUE TITLE
Currency to Crypto conversion 

### ISSUE THREAD

**Issue by GreenCup718** [biati-digital/alfred-calculate-anything#72]
Hi. The plugin seems to work when converting from crypto to a currency, but not the other way around. 
If i wanted to send you $20 in BTC, i should be able to type 20usd to btc, and it would tell me the value in btc. Is this something you can add?

**Comment by GreenCup718** [comment]
Actually this seems to also be an issue with other currencies. I can type 100can to USD and get an answer, but if i type 100usd to can, i get nothing,

**Comment by biati-digital** [comment]
Hi @GreenCup718, yes this is not enabled for 2 reasons, I never needed this functionality and in almost 3 years you are the first person to ask for this.

It can be done but it will require some tests, I'll take a look at this when I've some free time.

**Comment by GreenCup718** [comment]
Oh. Hm. That's so strange. When i need to figure out how much crypto to send to someone, it seems like that would be the way to do it. 20USD to BTC. 
Anyway thanks

**Comment by oluckyman** [comment]
I installed the workflow 20 mins ago exactly for the quick currency ←→ crypto conversions, and here I am, missing this feature too!

ps. thanks for your efforts! great tool!

**Comment by biati-digital** [comment]
Hi @oluckyman, that's planned, i'm working on the new version for Alfred 5 (with the new configuration options) and hopefully this will be included.

**Comment by biati-digital** [comment]
This was added in the latest version [4.0.0](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.0). Please read the release to see what's new.
