### ISSUE TITLE
Currency symbols not working

### ISSUE THREAD

**Issue by khw77** [biati-digital/alfred-calculate-anything#77]
100 euros to dollars works fine,  but 100 € to $ does not. Symbols are ignored and only action offered is to copy 100 to the clipboard
<img width="720" alt="Screenshot 2022-08-18 at 23 27 15" src="https://user-images.githubusercontent.com/24650667/185506045-4aec966b-4789-435b-9ffe-c4ad314dbe32.png">

**Comment by biati-digital** [comment]
Please use the bug report template, issues without all the required information will be closed automatically.
