### ISSUE TITLE
Feature Request: convert to ft and inches

### ISSUE THREAD

**Issue by DR2000** [biati-digital/alfred-calculate-anything#8]
The best example is wolfram alpha:
query: 50 inches to ft and inches
returns: 4' 2"

Is there a way to do this already that I'm missing? If not, it would be really nice to add this.

**Comment by biati-digital** [comment]
I think this is doable, i'll take a look as soon as i've some free time.

**Comment by arvidbjorkstrom** [comment]
I've written a solution for getting the fraction of a number displayed as a sub-unit (see the mention above)

**Comment by arvidbjorkstrom** [comment]
![SCR-20230207-i9h](https://user-images.githubusercontent.com/255458/217241170-9fa4e848-117e-4001-ae86-e505d1ca283e.png)

**Comment by biati-digital** [comment]
The solution by @arvidbjorkstrom  it's now included in the latest version of the workflow. [4.0.0](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.0)
