### ISSUE TITLE
£ symbol doesn't work.

### ISSUE THREAD

**Issue by polyartin** [biati-digital/alfred-calculate-anything#89]
All the other keys work € / $ etc, but £ doesn't.
Guessing it's to do with brexit. 

Any support warmly welcomed :)

**Comment by biati-digital** [comment]
I'm unable to replicate, please use the bug report template to provide the necessary info.

![CleanShot 2023-02-06 at 21 56 55](https://user-images.githubusercontent.com/1219228/217144613-51c06075-4507-4720-8772-8d89b9f2a3c3.png)
