### ISSUE TITLE
Changes Icon

### ISSUE THREAD

**Issue by yli** [biati-digital/alfred-calculate-anything#9]
Would you mind to change the icon (e.g. another calculator icon)? 

Now it's the same as the Alfred official calculator icon and sometimes confuses me:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/32441766/92324330-5408f580-f073-11ea-83e7-ceb3fff7c410.png">

**Comment by biati-digital** [comment]
That's the Mac OS Calculator app icon, Alfred uses it for calculations so.... i like the icon becase it's a native OS icon designed by Apple and fits the workflow name.

i will not change the icon but you can set any icon you want, just open Alfred and in the workflows list double click calculate anything, a small window will open and you can drag any icon you want.

![Screen Shot 2020-09-06 at 10 27 22](https://user-images.githubusercontent.com/1219228/92329205-8ee73b00-f02b-11ea-8d59-f1b0cb63a1c0.png)

**Comment by yli** [comment]
Sure, thanks for your suggestions! 

Just curious: If I change the icon locally, will it change back to your icon once you release a new version? I'm a newbie to the workflow update.
