### ISSUE TITLE
Precomposed form characters in utf-8

### ISSUE THREAD

**Issue by arvidbjorkstrom** [biati-digital/alfred-calculate-anything#90]
https://github.com/biati-digital/alfred-calculate-anything/blob/01efe495786673a2de2836ed2826d0f9a13c7899/alfred/Alfred.php#L290-L301
I'm not 100% sure why this part of the code exists. But if it relates to the issue of non regex matching seemingly identical characters I've been having with my Swedish translation and version of composed characters in utf-8 a better way to do this is to normalize the input.

```php
$clean = normalizer_normalize($clean);
```

**The fleshed out version:**
The issue I've been having with my Swedish translation is that input words with a non ASCII character (åäö) wouldn't match what should be the same word in the `sv_SE-keys.php` file. (For example "hästkrafter" not matching seemingly exact same word)
After going down the rabbit hole debugging this the thing that led to the solution was that the hex value of the words actually didn't match. They were both correct utf-8, but the word from the keys-file being `68C3A473746B726166746572` and the word from the input was `6861CC8873746B726166746572`. After reading up a bit 61CC88 is the canonical composed representation - with a separate 'a' and separat ¨(dots) and C3A4 is the precomposed version of the whole 'ä' character.
The solution to make them match is to normalize the utf-8 parsing all characters into precomposed form.

**Comment by biati-digital** [comment]
i don't remember exactly why we added that code, it was in an older Alfred version and the workflow worked different 5 years ago, and to be honest i thought the chances of someone contributing a translation was close to cero so i was happy if it worked in english and spanish.

Changing to `normalizer_normalize` will break some of the Spanish translations but i can updated it. I just need to make some tests to make sure it does not break other things. 

i'll check your PR and continue the conversation there.

**Comment by biati-digital** [comment]
I thought the PR removed the `urlencode` and other code, my mistake, it seems to be working without problems.
