### ISSUE TITLE
Spanish phrase in English translation file

### ISSUE THREAD

**Issue by arvidbjorkstrom** [biati-digital/alfred-calculate-anything#91]
https://github.com/biati-digital/alfred-calculate-anything/blob/01efe495786673a2de2836ed2826d0f9a13c7899/lang/en_EN.php#L239

Forgotten Spanish in English translation file. Should be `'cmd' => 'Action this item to copy the amount with no format',` to stay consistent.

**Comment by biati-digital** [comment]
Thank's for noticing this, i've added the correct text.
