### ISSUE TITLE
Subtitle misleading

### ISSUE THREAD

**Issue by arvidbjorkstrom** [biati-digital/alfred-calculate-anything#97]
https://github.com/biati-digital/alfred-calculate-anything/blob/01efe495786673a2de2836ed2826d0f9a13c7899/workflow/tools/units.php#L228

This is an error message without anything to copy so the subtitle shouldn't be to copy.
Proposed replacement:
```php
    'subtitle' => '',
```

**Comment by biati-digital** [comment]
thank's, you are correct, your proposed replacement has been implemented.
